#YamlMime:Yaml
#ms.openlocfilehash: 16dc8b4edff051168ef33aca865771632e9e8a6e
#ms.sourcegitcommit: 57d343a6c7c2aa43c9f007d7823891d2141eb471
#ms.translationtype: HT
#ms.contentlocale: it-IT
#ms.lasthandoff: 07/01/2021
#ms.locfileid: "113169686"
trigger:
- '*'
pool:
  vmImage: ubuntu-20.04
  demands:
  - npm
variables:
  buildConfiguration: Release
  wwwrootDir: Tailspin.SpaceGame.Web/wwwroot
  dotnetSdkVersion: 5.x
steps:
- task: UseDotNet@2
  displayName: Use .NET SDK $(dotnetSdkVersion)
  inputs:
    version: $(dotnetSdkVersion)
- task: Npm@1
  displayName: Run npm install
  inputs:
    verbose: false
- script: ./node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)
  displayName: Compile Sass assets
- task: gulp@1
  displayName: Run gulp tasks
- script: echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
  displayName: Write build info
  workingDirectory: $(wwwrootDir)
- task: DotNetCoreCLI@2
  displayName: Restore project dependencies
  inputs:
    command: restore
    projects: '**/*.csproj'
- template: templates/build.yml
  parameters:
    buildConfiguration: Debug
- template: templates/build.yml
  parameters:
    buildConfiguration: Release
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()
