# YamlMime:Yaml
#ms.openlocfilehash: 1f16ddecd0df0d946cdcc20c946ed58193f9f1c2
#ms.sourcegitcommit: 57d343a6c7c2aa43c9f007d7823891d2141eb471
#ms.translationtype: HT
#ms.contentlocale: it-IT
#ms.lasthandoff: 07/01/2021
#ms.locfileid: "113169686"
parameters:
  buildConfiguration: Release
steps:
- task: DotNetCoreCLI@2
  displayName: Build the project - ${{ parameters.buildConfiguration }}
  inputs:
    command: build
    arguments: --no-restore --configuration ${{ parameters.buildConfiguration }}
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Publish the project - ${{ parameters.buildConfiguration }}
  inputs:
    command: publish
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: --no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}
    zipAfterPublish: true